import copy

from peptacular.constants import PROTEASES

MAX_PROTEIN_LEN = 2_500
MAX_PROTEIN_INPUT_LENGTH = 10_000

MIN_MISSED_CLEAVAGES = 0
MAX_MISSED_CLEAVAGES = 5
DEFAULT_MISSED_CLEAVAGES = 1
MISSED_CLEAVAGES_STEP = 1

MIN_PEPTIDE_LEN = 1
MAX_PEPTIDE_LEN = 50
DEFAULT_MIN_PEPTIDE_LEN = 7
DEFAULT_MAX_PEPTIDE_LEN = 30
PEPTIDE_LEN_STEP = 1

MIN_PEPTIDE_MASS = 0.0
MAX_PEPTIDE_MASS = 10_000.0
DEFAULT_MIN_PEPTIDE_MASS = 500.0
DEFAULT_MAX_PEPTIDE_MASS = 6_000.0
PEPTIDE_MASS_STEP = 100.0

DEFAULT_PROTEASES = ["trypsin/P"]
DEFAULT_PROTEIN_ID = ''
DEFAULT_PROTEIN_ID_PLACEHOLDER = 'P12345'
DEFAULT_CUSTOM_REGEX = ''

MASS_TYPE_OPTIONS = ['monoisotopic', 'average']
DEFAULT_MASS_TYPE = 'monoisotopic'
DEFAULT_MASS_TYPE_INDEX = MASS_TYPE_OPTIONS.index(DEFAULT_MASS_TYPE)

MIN_STATIC_MODS = 0
MAX_STATIC_MODS = 10
DEFAULT_STATIC_MODS = 1
STATIC_MODS_STEP = 1

MIN_CHARGE = 1
MAX_CHARGE = 10
DEFAULT_MIN_CHARGE = 2
DEFAULT_MAX_CHARGE = 5
CHARGE_STEP = 1

MIN_MZ = 0.0
MAX_MZ = 10_000.0
DEFAULT_MIN_MZ = 200.0
DEFAULT_MAX_MZ = 1_800.0
MZ_STEP = 100.0

# Default settings for checkboxes
DEFAULT_SEMI_ENZYMATIC = False
DEFAULT_INFER_CHARGE = False
DEFAULT_INFER_RT = True
DEFAULT_FILTER_INVALID_RT = False
DEFAULT_INFER_ION_MOBILITY = True
DEFAULT_INFER_PROTEOTYPIC = True
DEFAULT_REMOVE_NON_PROTEOTYPIC = False

# Default values for numeric inputs
DEFAULT_PLUS_MINUS_CHARGE = 0
DEFAULT_RT = 60
DEFAULT_PROTEOTYPIC_THRESHOLD = 0.5

# Default static modifications
DEFAULT_STATIC_MODS_DATA = {"Amino Acids": ["C"], "Mass (Da)": [57.02146]}

CMAP = 'hot'

DEFAULT_PROTEIN_SEQUENCE = """
MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFS
NVTWFHAIHVSGTNGTKRFDNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDSKTQSLLIV
NNATNVVIKVCEFQFCNDPFLGVYYHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLE
GKQGNFKNLREFVFKNIDGYFKIYSKHTPINLVRDLPQGFSALEPLVDLPIGINITRFQT
LLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETK
CTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISN
CVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIAD
YNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPC
NGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVN
FNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITP
GTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSY
ECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTI
SVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQE
VFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDC
LGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAM
QMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALN
TLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRA
SANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPA
ICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDP
LQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDL
QELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDD
SEPVLKGVKLHYT
"""

DEFAULT_PROTEIN_SEQUENCE = DEFAULT_PROTEIN_SEQUENCE.replace('\n', '').replace('', '')

LINK = 'https://pep-frag.streamlit.app/'

VALID_PROTEASES = copy.deepcopy(PROTEASES)
VALID_PROTEASES.pop('non-specific', None)


